apiVersion: v1
kind: ConfigMap
metadata:
  name: mediator-config
  labels:
    # This includes a newline, so ko sees this as valid yaml
    # {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  config.yaml: |
    {{ .Files.Get "config.yaml.example" | nindent 4 }}
  overrides.yaml: |
    {{ .Values.extra_config | nindent 4}}