apiVersion: batch/v1
kind: Job
metadata:
  name: mediator
  labels:
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/name: mediator
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: db-init
    spec:
      serviceAccountName: mediator
      restartPolicy: Never
      containers:
        - name: mediator-dbinit
          # restricted security context:
          # https://kubernetes.io/docs/concepts/security/pod-security-standards/
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          image: ko://github.com/stacklok/mediator/cmd/server
          args:
          - "migrate"
          - "up"
          - "--yes"
          - "--db-host={{ .Values.db.host }}"
          - "--config=/config/config.yaml"
          # ko will always specify a digest, so we don't need to worry about
          # CRI image caching
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1
              memory: 200Mi
            limits:
              cpu: 1
              memory: 300Mi
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
      - name: config
        configMap:
          name: mediator-config
          items:
          - key: config.yaml
            path: config.yaml
 