# Post-submit and daily build and publish of the Helm chart and Docker container
# This is a separate workflow than image-build.yml because image-build.yml is
# run in the PR context, and those runs aren't allowed package:write permissions if
# the source is a fork(GitHub errors and invalidates the entire workflow if you try).
name: Publish Helm Chart
on:
  push:
    branches:
    -  main

  schedule:
    # Weekdays at noon GMT
    - cron: '00 12 * * 1-5'

jobs:
  check-helm:
    name: Build Helm chart
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6

      - uses: azure/setup-helm@v3
        with:
          version: v3.12.2

      - name: Helm Login
        # ko can pick up tokens ambiently from the GitHub Actions environment, but
        # Helm needs explicit login
        run: |
          helm registry login ghcr.io --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}

      - run: |
          make helm
          (cd deployment/helm && helm push mediator-*.tgz oci://$KO_DOCKER_REPO/helm)
        env:
          KO_DOCKER_REPO: "ghcr.io/stacklok/mediator"
