---
# This test verifies that Pull Requests don't touch the merged database migrations.
# Folks should now only be adding new migrations to the `database/migrations/` directory.
name: Database Migrations Untouched

on:
  pull_request:
    paths:
      - 'database/migrations/*'
      - '.github/workflows/migrate-touch.yml'

jobs:
  verify-migrations:
    name: Don't touch existing migrations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Migration Files
      run: |
        modified_files=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} -- 'database/migrations/' | grep '.sql' || true)

        if [ -n "$modified_files" ]; then
          echo "Error: Modifying existing migration files is not allowed."
          echo "Modified files:"
          echo "$modified_files"
          exit 1
        fi
      shell: bash
