on:
  workflow_call:
jobs:
  code-security-scan:
    runs-on: ubuntu-latest
    name: Code Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Security Scan
        uses: aquasecurity/trivy-action@master  # Trivy Action doesn't have a stable release yet
        with:
          scan-type: 'fs'
          scanners: vuln,secret
          trivy-config: .trivy.yml
          exit-code: 1
          ignore-unfixed: true

  helm-security-scan:
    runs-on: ubuntu-latest
    name: Helm Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Security Scan
        uses: aquasecurity/trivy-action@master  # Trivy Action doesn't have a stable release yet
        with:
          scan-type: 'config'
          trivy-config: .trivy.yml
          exit-code: 1
          ignore-unfixed: true
          scan-ref: ./deployment/helm